name: Rust checks

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable

      - name: Check formatting
        run: cargo fmt -- --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable

      - name: Check for linting errors
        run: cargo clippy -- -D warnings
